name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build the CI environment in all examples
  build:
    runs-on: ubuntu-latest

    # run all examples in a matrix
    strategy:
      matrix:
        platformio_ini: [ ./examples/**/platformio.ini ]

    steps:
      # checkout the repository
      - uses: actions/checkout@v4
      
      # enable caching of pip and platformio
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      
      # install python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # install platformio
      - name: Install PlatformIO core
        run: pip install --upgrade platformio
      
      # print the platformio.ini file path
      - name: Print platformio ini
        run: echo ${{ matrix.platformio_ini }}

      # build the 'CI' environment
      - name: Build 'ci' environment
        run: pio run --project-dir ${{ matrix.platformio_ini }} --environment ci
